// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rtnorm
double rtnorm(double mu, double sigma, double a, double b);
RcppExport SEXP _ZoopFit_rtnorm(SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm(mu, sigma, a, b));
    return rcpp_result_gen;
END_RCPP
}
// dtnorm
double dtnorm(double x, double mu, double sigma, double a, double b);
RcppExport SEXP _ZoopFit_dtnorm(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dtnorm(x, mu, sigma, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rfnorm
double rfnorm(double mu, double sigma);
RcppExport SEXP _ZoopFit_rfnorm(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rfnorm(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rWishart
arma::mat rWishart(arma::mat V, int p, double n);
RcppExport SEXP _ZoopFit_rWishart(SEXP VSEXP, SEXP pSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rWishart(V, p, n));
    return rcpp_result_gen;
END_RCPP
}
// productNormals
arma::vec productNormals(arma::vec mu, arma::vec prec);
RcppExport SEXP _ZoopFit_productNormals(SEXP muSEXP, SEXP precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prec(precSEXP);
    rcpp_result_gen = Rcpp::wrap(productNormals(mu, prec));
    return rcpp_result_gen;
END_RCPP
}
// meanGP
double meanGP(arma::vec vect, double sigma2inv, arma::mat Rinv, double a, double b2inv);
RcppExport SEXP _ZoopFit_meanGP(SEXP vectSEXP, SEXP sigma2invSEXP, SEXP RinvSEXP, SEXP aSEXP, SEXP b2invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vect(vectSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2inv(sigma2invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rinv(RinvSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b2inv(b2invSEXP);
    rcpp_result_gen = Rcpp::wrap(meanGP(vect, sigma2inv, Rinv, a, b2inv));
    return rcpp_result_gen;
END_RCPP
}
// precGP
double precGP(arma::vec vect, double mean, arma::mat Rinv, double a, double b);
RcppExport SEXP _ZoopFit_precGP(SEXP vectSEXP, SEXP meanSEXP, SEXP RinvSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vect(vectSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rinv(RinvSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(precGP(vect, mean, Rinv, a, b));
    return rcpp_result_gen;
END_RCPP
}
// lmS
arma::mat lmS(arma::vec Y, arma::vec X, arma::vec inits, double na, double nb, double ga, double gb, int N, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_lmS(SEXP YSEXP, SEXP XSEXP, SEXP initsSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP NSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(lmS(Y, X, inits, na, nb, ga, gb, N, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// lmM
arma::mat lmM(arma::vec Y, arma::mat X, arma::vec inits, double na, double nb, double ga, double gb, int p, int N, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_lmM(SEXP YSEXP, SEXP XSEXP, SEXP initsSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP pSEXP, SEXP NSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(lmM(Y, X, inits, na, nb, ga, gb, p, N, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// splmM
arma::mat splmM(arma::vec Y, arma::mat X, arma::mat I, arma::uvec si, arma::mat Rb0, double Rb0sum, arma::vec inits, double na, double nb, double ga, double gb, int p, int n, int N, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_splmM(SEXP YSEXP, SEXP XSEXP, SEXP ISEXP, SEXP siSEXP, SEXP Rb0SEXP, SEXP Rb0sumSEXP, SEXP initsSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP pSEXP, SEXP nSEXP, SEXP NSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rb0(Rb0SEXP);
    Rcpp::traits::input_parameter< double >::type Rb0sum(Rb0sumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(splmM(Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// splmS
arma::mat splmS(arma::vec Y, arma::vec X, arma::mat I, arma::uvec si, arma::mat dist, arma::vec inits, double sd, double na, double nb, double ga, double gb, double Umin, double Umax, int n, int N, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_splmS(SEXP YSEXP, SEXP XSEXP, SEXP ISEXP, SEXP siSEXP, SEXP distSEXP, SEXP initsSEXP, SEXP sdSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP UminSEXP, SEXP UmaxSEXP, SEXP nSEXP, SEXP NSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< double >::type Umin(UminSEXP);
    Rcpp::traits::input_parameter< double >::type Umax(UmaxSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(splmS(Y, X, I, si, dist, inits, sd, na, nb, ga, gb, Umin, Umax, n, N, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// splmMRnoAR
arma::mat splmMRnoAR(arma::vec Y, arma::mat X, arma::mat I, arma::uvec si, arma::mat Rb0, double Rb0sum, arma::vec inits, double na, double nb, double ga, double gb, int p, int n, int N, int T, arma::mat Xt, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_splmMRnoAR(SEXP YSEXP, SEXP XSEXP, SEXP ISEXP, SEXP siSEXP, SEXP Rb0SEXP, SEXP Rb0sumSEXP, SEXP initsSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP pSEXP, SEXP nSEXP, SEXP NSEXP, SEXP TSEXP, SEXP XtSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rb0(Rb0SEXP);
    Rcpp::traits::input_parameter< double >::type Rb0sum(Rb0sumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(splmMRnoAR(Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// splmMR
arma::mat splmMR(arma::vec Y, arma::mat X, arma::mat I, arma::uvec si, arma::mat Rb0, double Rb0sum, arma::vec inits, double na, double nb, double ga, double gb, int p, int n, int N, int T, arma::mat Xt, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_splmMR(SEXP YSEXP, SEXP XSEXP, SEXP ISEXP, SEXP siSEXP, SEXP Rb0SEXP, SEXP Rb0sumSEXP, SEXP initsSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP pSEXP, SEXP nSEXP, SEXP NSEXP, SEXP TSEXP, SEXP XtSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rb0(Rb0SEXP);
    Rcpp::traits::input_parameter< double >::type Rb0sum(Rb0sumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(splmMR(Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// splmMR2
arma::mat splmMR2(arma::vec Y, arma::mat X, arma::mat I, arma::uvec si, arma::mat Rb0, double Rb0sum, arma::vec inits, double na, double nb, double ga, double gb, int p, int n, int N, int T, arma::mat Xt, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_splmMR2(SEXP YSEXP, SEXP XSEXP, SEXP ISEXP, SEXP siSEXP, SEXP Rb0SEXP, SEXP Rb0sumSEXP, SEXP initsSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP pSEXP, SEXP nSEXP, SEXP NSEXP, SEXP TSEXP, SEXP XtSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rb0(Rb0SEXP);
    Rcpp::traits::input_parameter< double >::type Rb0sum(Rb0sumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(splmMR2(Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// splmSS
arma::mat splmSS(arma::vec Y, arma::vec X, arma::mat I, arma::uvec si, arma::mat dist, arma::vec init, double sd, double na, double nb, double ga, double gb, double Umin, double Umax, int n, int N, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_splmSS(SEXP YSEXP, SEXP XSEXP, SEXP ISEXP, SEXP siSEXP, SEXP distSEXP, SEXP initSEXP, SEXP sdSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP UminSEXP, SEXP UmaxSEXP, SEXP nSEXP, SEXP NSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< double >::type Umin(UminSEXP);
    Rcpp::traits::input_parameter< double >::type Umax(UmaxSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(splmSS(Y, X, I, si, dist, init, sd, na, nb, ga, gb, Umin, Umax, n, N, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// calCor
arma::mat calCor(arma::vec Y, arma::vec X, arma::mat I, arma::uvec si, arma::mat dist, arma::vec init, double sd, double na, double nb, double ga, double gb, int n, int N, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_calCor(SEXP YSEXP, SEXP XSEXP, SEXP ISEXP, SEXP siSEXP, SEXP distSEXP, SEXP initSEXP, SEXP sdSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP nSEXP, SEXP NSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(calCor(Y, X, I, si, dist, init, sd, na, nb, ga, gb, n, N, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// AR1
arma::vec AR1(arma::vec Y, arma::vec init, double na, double nb, double ga, double gb, int T);
RcppExport SEXP _ZoopFit_AR1(SEXP YSEXP, SEXP initSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(AR1(Y, init, na, nb, ga, gb, T));
    return rcpp_result_gen;
END_RCPP
}
// biAR1
arma::vec biAR1(arma::vec Y0, arma::vec Y1, arma::vec init, double na1, double na, double nb, int T);
RcppExport SEXP _ZoopFit_biAR1(SEXP Y0SEXP, SEXP Y1SEXP, SEXP initSEXP, SEXP na1SEXP, SEXP naSEXP, SEXP nbSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y0(Y0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type na1(na1SEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(biAR1(Y0, Y1, init, na1, na, nb, T));
    return rcpp_result_gen;
END_RCPP
}
// calCorTime
arma::mat calCorTime(arma::vec Y, arma::vec X, arma::mat Xt, arma::mat I, arma::uvec si, arma::mat dist, arma::vec init, double sd, double na, double nb, double ga, double gb, int n, int T, int N, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_calCorTime(SEXP YSEXP, SEXP XSEXP, SEXP XtSEXP, SEXP ISEXP, SEXP siSEXP, SEXP distSEXP, SEXP initSEXP, SEXP sdSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP nSEXP, SEXP TSEXP, SEXP NSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(calCorTime(Y, X, Xt, I, si, dist, init, sd, na, nb, ga, gb, n, T, N, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// GibbsZoop4Cpp
arma::mat GibbsZoop4Cpp(arma::vec Y1, arma::vec Y2, arma::vec T1, arma::vec T2, arma::mat X, arma::mat Xeta, arma::mat XTEMP, arma::vec Rsum, double RsumTEMP, arma::cube R, arma::mat RTEMP, double dMax, arma::mat dY2, arma::mat dT2, double sd, arma::vec oneY1, arma::vec oneY2, arma::vec oneT1, arma::vec oneT2, arma::uvec indY1, arma::uvec indY2, arma::uvec indT1, arma::uvec indT2, arma::mat IY2, arma::mat IT2, arma::mat ITEMP, arma::uvec sY2, arma::uvec sT2, arma::uvec sTEMP, arma::mat Xt, int N, int NY1, int NY2, int NT1, int NT2, int T, arma::vec nt, double Ent, int nT2, int nY2, int nTEMP, int p, double na, double nb, double ga, double gb, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_GibbsZoop4Cpp(SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP XSEXP, SEXP XetaSEXP, SEXP XTEMPSEXP, SEXP RsumSEXP, SEXP RsumTEMPSEXP, SEXP RSEXP, SEXP RTEMPSEXP, SEXP dMaxSEXP, SEXP dY2SEXP, SEXP dT2SEXP, SEXP sdSEXP, SEXP oneY1SEXP, SEXP oneY2SEXP, SEXP oneT1SEXP, SEXP oneT2SEXP, SEXP indY1SEXP, SEXP indY2SEXP, SEXP indT1SEXP, SEXP indT2SEXP, SEXP IY2SEXP, SEXP IT2SEXP, SEXP ITEMPSEXP, SEXP sY2SEXP, SEXP sT2SEXP, SEXP sTEMPSEXP, SEXP XtSEXP, SEXP NSEXP, SEXP NY1SEXP, SEXP NY2SEXP, SEXP NT1SEXP, SEXP NT2SEXP, SEXP TSEXP, SEXP ntSEXP, SEXP EntSEXP, SEXP nT2SEXP, SEXP nY2SEXP, SEXP nTEMPSEXP, SEXP pSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xeta(XetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XTEMP(XTEMPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rsum(RsumSEXP);
    Rcpp::traits::input_parameter< double >::type RsumTEMP(RsumTEMPSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RTEMP(RTEMPSEXP);
    Rcpp::traits::input_parameter< double >::type dMax(dMaxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dY2(dY2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dT2(dT2SEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY1(oneY1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY2(oneY2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT1(oneT1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT2(oneT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY1(indY1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY2(indY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT1(indT1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT2(indT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type IY2(IY2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type IT2(IT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ITEMP(ITEMPSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sY2(sY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sT2(sT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sTEMP(sTEMPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type NY1(NY1SEXP);
    Rcpp::traits::input_parameter< int >::type NY2(NY2SEXP);
    Rcpp::traits::input_parameter< int >::type NT1(NT1SEXP);
    Rcpp::traits::input_parameter< int >::type NT2(NT2SEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< double >::type Ent(EntSEXP);
    Rcpp::traits::input_parameter< int >::type nT2(nT2SEXP);
    Rcpp::traits::input_parameter< int >::type nY2(nY2SEXP);
    Rcpp::traits::input_parameter< int >::type nTEMP(nTEMPSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsZoop4Cpp(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// GibbsZoop3Cpp
arma::mat GibbsZoop3Cpp(arma::vec Y1, arma::vec Y2, arma::vec T1, arma::vec T2, arma::mat X, arma::mat Xeta, arma::mat XTEMP, arma::vec Rsum, double RsumTEMP, arma::cube R, arma::mat RTEMP, double dMax, arma::mat dY2, arma::mat dT2, double sd, arma::vec oneY1, arma::vec oneY2, arma::vec oneT1, arma::vec oneT2, arma::uvec indY1, arma::uvec indY2, arma::uvec indT1, arma::uvec indT2, arma::mat IY2, arma::mat IT2, arma::mat ITEMP, arma::uvec sY2, arma::uvec sT2, arma::uvec sTEMP, arma::mat Xt, int N, int NY1, int NY2, int NT1, int NT2, int T, arma::vec nt, double Ent, int nT2, int nY2, int nTEMP, int p, double na, double nb, double ga, double gb, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_GibbsZoop3Cpp(SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP XSEXP, SEXP XetaSEXP, SEXP XTEMPSEXP, SEXP RsumSEXP, SEXP RsumTEMPSEXP, SEXP RSEXP, SEXP RTEMPSEXP, SEXP dMaxSEXP, SEXP dY2SEXP, SEXP dT2SEXP, SEXP sdSEXP, SEXP oneY1SEXP, SEXP oneY2SEXP, SEXP oneT1SEXP, SEXP oneT2SEXP, SEXP indY1SEXP, SEXP indY2SEXP, SEXP indT1SEXP, SEXP indT2SEXP, SEXP IY2SEXP, SEXP IT2SEXP, SEXP ITEMPSEXP, SEXP sY2SEXP, SEXP sT2SEXP, SEXP sTEMPSEXP, SEXP XtSEXP, SEXP NSEXP, SEXP NY1SEXP, SEXP NY2SEXP, SEXP NT1SEXP, SEXP NT2SEXP, SEXP TSEXP, SEXP ntSEXP, SEXP EntSEXP, SEXP nT2SEXP, SEXP nY2SEXP, SEXP nTEMPSEXP, SEXP pSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xeta(XetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XTEMP(XTEMPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rsum(RsumSEXP);
    Rcpp::traits::input_parameter< double >::type RsumTEMP(RsumTEMPSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RTEMP(RTEMPSEXP);
    Rcpp::traits::input_parameter< double >::type dMax(dMaxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dY2(dY2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dT2(dT2SEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY1(oneY1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY2(oneY2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT1(oneT1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT2(oneT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY1(indY1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY2(indY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT1(indT1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT2(indT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type IY2(IY2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type IT2(IT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ITEMP(ITEMPSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sY2(sY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sT2(sT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sTEMP(sTEMPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type NY1(NY1SEXP);
    Rcpp::traits::input_parameter< int >::type NY2(NY2SEXP);
    Rcpp::traits::input_parameter< int >::type NT1(NT1SEXP);
    Rcpp::traits::input_parameter< int >::type NT2(NT2SEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< double >::type Ent(EntSEXP);
    Rcpp::traits::input_parameter< int >::type nT2(nT2SEXP);
    Rcpp::traits::input_parameter< int >::type nY2(nY2SEXP);
    Rcpp::traits::input_parameter< int >::type nTEMP(nTEMPSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsZoop3Cpp(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// GibbsZoop2Cpp
arma::mat GibbsZoop2Cpp(arma::vec Y1, arma::vec Y2, arma::vec T1, arma::vec T2, arma::mat X, arma::mat Xeta, arma::mat XTEMP, arma::vec Rsum, double RsumTEMP, arma::cube R, arma::mat RTEMP, double dMax, arma::mat dY2, arma::mat dT2, double sd, arma::vec oneY1, arma::vec oneY2, arma::vec oneT1, arma::vec oneT2, arma::uvec indY1, arma::uvec indY2, arma::uvec indT1, arma::uvec indT2, arma::mat IY2, arma::mat IT2, arma::mat ITEMP, arma::uvec sY2, arma::uvec sT2, arma::uvec sTEMP, arma::mat Xt, int N, int NY1, int NY2, int NT1, int NT2, int T, arma::vec nt, double Ent, int nT2, int nY2, int nTEMP, int p, double na, double nb, double ga, double gb, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_GibbsZoop2Cpp(SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP XSEXP, SEXP XetaSEXP, SEXP XTEMPSEXP, SEXP RsumSEXP, SEXP RsumTEMPSEXP, SEXP RSEXP, SEXP RTEMPSEXP, SEXP dMaxSEXP, SEXP dY2SEXP, SEXP dT2SEXP, SEXP sdSEXP, SEXP oneY1SEXP, SEXP oneY2SEXP, SEXP oneT1SEXP, SEXP oneT2SEXP, SEXP indY1SEXP, SEXP indY2SEXP, SEXP indT1SEXP, SEXP indT2SEXP, SEXP IY2SEXP, SEXP IT2SEXP, SEXP ITEMPSEXP, SEXP sY2SEXP, SEXP sT2SEXP, SEXP sTEMPSEXP, SEXP XtSEXP, SEXP NSEXP, SEXP NY1SEXP, SEXP NY2SEXP, SEXP NT1SEXP, SEXP NT2SEXP, SEXP TSEXP, SEXP ntSEXP, SEXP EntSEXP, SEXP nT2SEXP, SEXP nY2SEXP, SEXP nTEMPSEXP, SEXP pSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xeta(XetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XTEMP(XTEMPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rsum(RsumSEXP);
    Rcpp::traits::input_parameter< double >::type RsumTEMP(RsumTEMPSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RTEMP(RTEMPSEXP);
    Rcpp::traits::input_parameter< double >::type dMax(dMaxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dY2(dY2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dT2(dT2SEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY1(oneY1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY2(oneY2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT1(oneT1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT2(oneT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY1(indY1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY2(indY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT1(indT1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT2(indT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type IY2(IY2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type IT2(IT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ITEMP(ITEMPSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sY2(sY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sT2(sT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sTEMP(sTEMPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type NY1(NY1SEXP);
    Rcpp::traits::input_parameter< int >::type NY2(NY2SEXP);
    Rcpp::traits::input_parameter< int >::type NT1(NT1SEXP);
    Rcpp::traits::input_parameter< int >::type NT2(NT2SEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< double >::type Ent(EntSEXP);
    Rcpp::traits::input_parameter< int >::type nT2(nT2SEXP);
    Rcpp::traits::input_parameter< int >::type nY2(nY2SEXP);
    Rcpp::traits::input_parameter< int >::type nTEMP(nTEMPSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsZoop2Cpp(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// GibbsZoop1Cpp
arma::mat GibbsZoop1Cpp(arma::vec Y1, arma::vec Y2, arma::vec T1, arma::vec T2, arma::mat X, arma::mat Xeta, arma::mat XTEMP, arma::vec Rsum, double RsumTEMP, arma::cube R, arma::mat RTEMP, double dMax, arma::mat dY2, arma::mat dT2, double sd, arma::vec oneY1, arma::vec oneY2, arma::vec oneT1, arma::vec oneT2, arma::uvec indY1, arma::uvec indY2, arma::uvec indT1, arma::uvec indT2, arma::mat IY2, arma::mat IT2, arma::mat ITEMP, arma::uvec sY2, arma::uvec sT2, arma::uvec sTEMP, arma::mat Xt, int N, int NY1, int NY2, int NT1, int NT2, int T, arma::vec nt, double Ent, int nT2, int nY2, int nTEMP, int p, double na, double nb, double ga, double gb, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_GibbsZoop1Cpp(SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP XSEXP, SEXP XetaSEXP, SEXP XTEMPSEXP, SEXP RsumSEXP, SEXP RsumTEMPSEXP, SEXP RSEXP, SEXP RTEMPSEXP, SEXP dMaxSEXP, SEXP dY2SEXP, SEXP dT2SEXP, SEXP sdSEXP, SEXP oneY1SEXP, SEXP oneY2SEXP, SEXP oneT1SEXP, SEXP oneT2SEXP, SEXP indY1SEXP, SEXP indY2SEXP, SEXP indT1SEXP, SEXP indT2SEXP, SEXP IY2SEXP, SEXP IT2SEXP, SEXP ITEMPSEXP, SEXP sY2SEXP, SEXP sT2SEXP, SEXP sTEMPSEXP, SEXP XtSEXP, SEXP NSEXP, SEXP NY1SEXP, SEXP NY2SEXP, SEXP NT1SEXP, SEXP NT2SEXP, SEXP TSEXP, SEXP ntSEXP, SEXP EntSEXP, SEXP nT2SEXP, SEXP nY2SEXP, SEXP nTEMPSEXP, SEXP pSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xeta(XetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XTEMP(XTEMPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rsum(RsumSEXP);
    Rcpp::traits::input_parameter< double >::type RsumTEMP(RsumTEMPSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RTEMP(RTEMPSEXP);
    Rcpp::traits::input_parameter< double >::type dMax(dMaxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dY2(dY2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dT2(dT2SEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY1(oneY1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY2(oneY2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT1(oneT1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT2(oneT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY1(indY1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY2(indY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT1(indT1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT2(indT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type IY2(IY2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type IT2(IT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ITEMP(ITEMPSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sY2(sY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sT2(sT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sTEMP(sTEMPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type NY1(NY1SEXP);
    Rcpp::traits::input_parameter< int >::type NY2(NY2SEXP);
    Rcpp::traits::input_parameter< int >::type NT1(NT1SEXP);
    Rcpp::traits::input_parameter< int >::type NT2(NT2SEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< double >::type Ent(EntSEXP);
    Rcpp::traits::input_parameter< int >::type nT2(nT2SEXP);
    Rcpp::traits::input_parameter< int >::type nY2(nY2SEXP);
    Rcpp::traits::input_parameter< int >::type nTEMP(nTEMPSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsZoop1Cpp(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// GibbsZoop0Cpp
arma::mat GibbsZoop0Cpp(arma::vec Y1, arma::vec Y2, arma::vec T1, arma::vec T2, arma::mat X, arma::mat Xeta, arma::mat XTEMP, arma::vec Rsum, double RsumTEMP, arma::cube R, arma::mat RTEMP, arma::vec oneY1, arma::vec oneY2, arma::vec oneT1, arma::vec oneT2, arma::uvec indY1, arma::uvec indY2, arma::uvec indT1, arma::uvec indT2, arma::mat ITEMP, arma::uvec sTEMP, arma::mat Xt, int N, int NY1, int NY2, int NT1, int NT2, int T, arma::vec nt, double Ent, int nTEMP, int p, double na, double nb, double ga, double gb, int nBurnin, int maxIter, int nThin, int nReport);
RcppExport SEXP _ZoopFit_GibbsZoop0Cpp(SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP XSEXP, SEXP XetaSEXP, SEXP XTEMPSEXP, SEXP RsumSEXP, SEXP RsumTEMPSEXP, SEXP RSEXP, SEXP RTEMPSEXP, SEXP oneY1SEXP, SEXP oneY2SEXP, SEXP oneT1SEXP, SEXP oneT2SEXP, SEXP indY1SEXP, SEXP indY2SEXP, SEXP indT1SEXP, SEXP indT2SEXP, SEXP ITEMPSEXP, SEXP sTEMPSEXP, SEXP XtSEXP, SEXP NSEXP, SEXP NY1SEXP, SEXP NY2SEXP, SEXP NT1SEXP, SEXP NT2SEXP, SEXP TSEXP, SEXP ntSEXP, SEXP EntSEXP, SEXP nTEMPSEXP, SEXP pSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP nBurninSEXP, SEXP maxIterSEXP, SEXP nThinSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xeta(XetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XTEMP(XTEMPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rsum(RsumSEXP);
    Rcpp::traits::input_parameter< double >::type RsumTEMP(RsumTEMPSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RTEMP(RTEMPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY1(oneY1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneY2(oneY2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT1(oneT1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type oneT2(oneT2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY1(indY1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indY2(indY2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT1(indT1SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indT2(indT2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ITEMP(ITEMPSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sTEMP(sTEMPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type NY1(NY1SEXP);
    Rcpp::traits::input_parameter< int >::type NY2(NY2SEXP);
    Rcpp::traits::input_parameter< int >::type NT1(NT1SEXP);
    Rcpp::traits::input_parameter< int >::type NT2(NT2SEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< double >::type Ent(EntSEXP);
    Rcpp::traits::input_parameter< int >::type nTEMP(nTEMPSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type na(naSEXP);
    Rcpp::traits::input_parameter< double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsZoop0Cpp(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, ITEMP, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ZoopFit_rtnorm", (DL_FUNC) &_ZoopFit_rtnorm, 4},
    {"_ZoopFit_dtnorm", (DL_FUNC) &_ZoopFit_dtnorm, 5},
    {"_ZoopFit_rfnorm", (DL_FUNC) &_ZoopFit_rfnorm, 2},
    {"_ZoopFit_rWishart", (DL_FUNC) &_ZoopFit_rWishart, 3},
    {"_ZoopFit_productNormals", (DL_FUNC) &_ZoopFit_productNormals, 2},
    {"_ZoopFit_meanGP", (DL_FUNC) &_ZoopFit_meanGP, 5},
    {"_ZoopFit_precGP", (DL_FUNC) &_ZoopFit_precGP, 5},
    {"_ZoopFit_lmS", (DL_FUNC) &_ZoopFit_lmS, 12},
    {"_ZoopFit_lmM", (DL_FUNC) &_ZoopFit_lmM, 13},
    {"_ZoopFit_splmM", (DL_FUNC) &_ZoopFit_splmM, 18},
    {"_ZoopFit_splmS", (DL_FUNC) &_ZoopFit_splmS, 19},
    {"_ZoopFit_splmMRnoAR", (DL_FUNC) &_ZoopFit_splmMRnoAR, 20},
    {"_ZoopFit_splmMR", (DL_FUNC) &_ZoopFit_splmMR, 20},
    {"_ZoopFit_splmMR2", (DL_FUNC) &_ZoopFit_splmMR2, 20},
    {"_ZoopFit_splmSS", (DL_FUNC) &_ZoopFit_splmSS, 19},
    {"_ZoopFit_calCor", (DL_FUNC) &_ZoopFit_calCor, 17},
    {"_ZoopFit_AR1", (DL_FUNC) &_ZoopFit_AR1, 7},
    {"_ZoopFit_biAR1", (DL_FUNC) &_ZoopFit_biAR1, 7},
    {"_ZoopFit_calCorTime", (DL_FUNC) &_ZoopFit_calCorTime, 19},
    {"_ZoopFit_GibbsZoop4Cpp", (DL_FUNC) &_ZoopFit_GibbsZoop4Cpp, 50},
    {"_ZoopFit_GibbsZoop3Cpp", (DL_FUNC) &_ZoopFit_GibbsZoop3Cpp, 50},
    {"_ZoopFit_GibbsZoop2Cpp", (DL_FUNC) &_ZoopFit_GibbsZoop2Cpp, 50},
    {"_ZoopFit_GibbsZoop1Cpp", (DL_FUNC) &_ZoopFit_GibbsZoop1Cpp, 50},
    {"_ZoopFit_GibbsZoop0Cpp", (DL_FUNC) &_ZoopFit_GibbsZoop0Cpp, 40},
    {NULL, NULL, 0}
};

RcppExport void R_init_ZoopFit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
