# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtnorm <- function(mu, sigma, a, b) {
    .Call('_ZoopFit_rtnorm', PACKAGE = 'ZoopFit', mu, sigma, a, b)
}

dtnorm <- function(x, mu, sigma, a, b) {
    .Call('_ZoopFit_dtnorm', PACKAGE = 'ZoopFit', x, mu, sigma, a, b)
}

rfnorm <- function(mu, sigma) {
    .Call('_ZoopFit_rfnorm', PACKAGE = 'ZoopFit', mu, sigma)
}

rWishart <- function(V, p, n) {
    .Call('_ZoopFit_rWishart', PACKAGE = 'ZoopFit', V, p, n)
}

#' COMPUTE PRODUCT OF NORMAL DENSITIES
#' @param mu vector mean
#' @param prec vector precision
#' @return vector(0) mean, vector(1) variance
productNormals <- function(mu, prec) {
    .Call('_ZoopFit_productNormals', PACKAGE = 'ZoopFit', mu, prec)
}

meanGP <- function(vect, sigma2inv, Rinv, a, b2inv) {
    .Call('_ZoopFit_meanGP', PACKAGE = 'ZoopFit', vect, sigma2inv, Rinv, a, b2inv)
}

precGP <- function(vect, mean, Rinv, a, b) {
    .Call('_ZoopFit_precGP', PACKAGE = 'ZoopFit', vect, mean, Rinv, a, b)
}

lmS <- function(Y, X, inits, na, nb, ga, gb, N, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_lmS', PACKAGE = 'ZoopFit', Y, X, inits, na, nb, ga, gb, N, nBurnin, maxIter, nThin, nReport)
}

lmM <- function(Y, X, inits, na, nb, ga, gb, p, N, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_lmM', PACKAGE = 'ZoopFit', Y, X, inits, na, nb, ga, gb, p, N, nBurnin, maxIter, nThin, nReport)
}

splmM <- function(Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_splmM', PACKAGE = 'ZoopFit', Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, nBurnin, maxIter, nThin, nReport)
}

splmS <- function(Y, X, I, si, dist, inits, sd, na, nb, ga, gb, Umin, Umax, n, N, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_splmS', PACKAGE = 'ZoopFit', Y, X, I, si, dist, inits, sd, na, nb, ga, gb, Umin, Umax, n, N, nBurnin, maxIter, nThin, nReport)
}

splmMRnoAR <- function(Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_splmMRnoAR', PACKAGE = 'ZoopFit', Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport)
}

splmMR <- function(Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_splmMR', PACKAGE = 'ZoopFit', Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport)
}

splmMR2 <- function(Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_splmMR2', PACKAGE = 'ZoopFit', Y, X, I, si, Rb0, Rb0sum, inits, na, nb, ga, gb, p, n, N, T, Xt, nBurnin, maxIter, nThin, nReport)
}

splmSS <- function(Y, X, I, si, dist, init, sd, na, nb, ga, gb, Umin, Umax, n, N, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_splmSS', PACKAGE = 'ZoopFit', Y, X, I, si, dist, init, sd, na, nb, ga, gb, Umin, Umax, n, N, nBurnin, maxIter, nThin, nReport)
}

calCor <- function(Y, X, I, si, dist, init, sd, na, nb, ga, gb, n, N, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_calCor', PACKAGE = 'ZoopFit', Y, X, I, si, dist, init, sd, na, nb, ga, gb, n, N, nBurnin, maxIter, nThin, nReport)
}

AR1 <- function(Y, init, na, nb, ga, gb, T) {
    .Call('_ZoopFit_AR1', PACKAGE = 'ZoopFit', Y, init, na, nb, ga, gb, T)
}

biAR1 <- function(Y0, Y1, init, na1, na, nb, T) {
    .Call('_ZoopFit_biAR1', PACKAGE = 'ZoopFit', Y0, Y1, init, na1, na, nb, T)
}

calCorTime <- function(Y, X, Xt, I, si, dist, init, sd, na, nb, ga, gb, n, T, N, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_calCorTime', PACKAGE = 'ZoopFit', Y, X, Xt, I, si, dist, init, sd, na, nb, ga, gb, n, T, N, nBurnin, maxIter, nThin, nReport)
}

GibbsZoop4Cpp <- function(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_GibbsZoop4Cpp', PACKAGE = 'ZoopFit', Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport)
}

GibbsZoop3Cpp <- function(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_GibbsZoop3Cpp', PACKAGE = 'ZoopFit', Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport)
}

GibbsZoop2Cpp <- function(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_GibbsZoop2Cpp', PACKAGE = 'ZoopFit', Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport)
}

GibbsZoop1Cpp <- function(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_GibbsZoop1Cpp', PACKAGE = 'ZoopFit', Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, dMax, dY2, dT2, sd, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, IY2, IT2, ITEMP, sY2, sT2, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nT2, nY2, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport)
}

GibbsZoop0Cpp <- function(Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, ITEMP, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport) {
    .Call('_ZoopFit_GibbsZoop0Cpp', PACKAGE = 'ZoopFit', Y1, Y2, T1, T2, X, Xeta, XTEMP, Rsum, RsumTEMP, R, RTEMP, oneY1, oneY2, oneT1, oneT2, indY1, indY2, indT1, indT2, ITEMP, sTEMP, Xt, N, NY1, NY2, NT1, NT2, T, nt, Ent, nTEMP, p, na, nb, ga, gb, nBurnin, maxIter, nThin, nReport)
}

